site_name: Learn
site_url: https://github.com/umarshai/learn
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
        - content.tooltips
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  # Page tree
nav:
  - Home: index.md
  - Angular:
      - RxJs: angular/rxjs.md
      - Share Data between Components: angular/share-data.md
      - Forms: angular/forms.md
      - Routing: angular/routing.md
      - Core: angular/core-concepts.md
      - Testing: angular/testing.md
      - NgRx: angular/ngRx.md
      - More: angular/more.md
  - JavaScript:
      - concepts: js/concepts.md
      - methods: js/methods.md
      - problems: js/problems.md
  - Html:
    - concepts: html/concepts.md
    - samples: html/samples.md
  - Css:
      - concepts: css/concepts.md
      - sass: css/sass.md
      - samples: css/samples.md
  - Typescript: typescript/typescript.md
  - Best Practices:
      - accesibility: best-practices/accesibility.md
      - accesibility: best-practices/seo.md
  - Interview Experiences:  interview-exp.md
markdown_extensions:
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.superfences
  - toc:
      permalink: true
      