site_name: Learn
site_url: https://github.com/umarshai/learn
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
        - content.tooltips
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  # Page tree
nav:
  - Home: index.md
  - Angular:
      - RxJs: angular/rxjs.md
      - Pipes-Intersceptors: angular/pipes-interceptors.md
      - Share Data between Components: angular/share-data.md
      - Forms: angular/forms.md
      - Routing: angular/routing.md
      - Core: angular/core-concepts.md
      - Testing: angular/testing.md
      - NgRx: angular/ngRx.md
      - More: angular/more.md
  - JavaScript:
      - concepts: js/concepts.md
      - methods: js/methods.md
      - problems: js/problems.md
  - Html:
    - concepts: html/concepts.md
    - samples: html/samples.md
  - Css:
      - concepts: css/concepts.md
      - sass: css/sass.md
      - samples: css/samples.md
  - Typescript: typescript/typescript.md
  - Best Practices:
      - Best Practices: best-practices/best-practices.md
      - Accesibility: best-practices/accesibility.md
      - Seo: best-practices/seo.md
  - Frequently Asked Questions:  interview-exp.md
  - Programs:
      - Interview Programs: programs/interview-programs.md
      - Practice Programs: programs/practice-programs.md
 
markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true
extra_javascript:
  - script/countdown.js      
      